param(
    [string]$EventKey,
    [string]$DataverseUrl = "https://org084965d9.crm.dynamics.com",
    [string]$SharePointSiteId = "52bda16d-2777-4304-9f5f-2cfdcb3ce4b0",
    [string]$RelativeUrl = "BIB_DOC_Expediente",
    [string]$Subject = "AUTO_DOC_LINK",
    [string]$Description = "Generated by SDU flow",
    [string]$EvidenceDir = "C:\CEO\watchdog\evidence",
    [string]$StatePath = "C:\CEO\watchdog\state\documentlocation-loop-state.json",
    [string]$TelemetryPath = "C:\CEO\watchdog\logs\g6_loop_events.jsonl",
    [string]$LastStatePath = "C:\CEO\watchdog\state\g6_loop_last.json",
    [string]$WatchdogPath = "C:\CEO\watchdog\watchdog-sharepoint-link.ps1",
    [string]$AzureCliPath = "C:\Program Files\Microsoft SDKs\Azure\CLI2\wbin\az.cmd",
    [ValidateSet("auto", "expediente", "adx")]
    [string]$AnchorMode = "auto",
    [switch]$AllowAdxCreate,
    [switch]$SkipWatchdog,
    [switch]$JsonOnly
)

$ErrorActionPreference = "Stop"

if (-not $EventKey) {
    $EventKey = "AUTO_DOC_LINK_" + (Get-Date -Format "yyyyMMdd_HHmmss")
}

$RunStamp = Get-Date -Format "yyyyMMdd_HHmmss"
$RunId = [guid]::NewGuid().ToString()
$StartedAt = (Get-Date).ToString("o")
$GraphRoot = "https://graph.microsoft.com/v1.0"
$EvidencePath = Join-Path $EvidenceDir "documentlocation_loop_run_$RunStamp.json"

$Result = [ordered]@{
    title = "SDU_G6_4_DOCUMENTLOCATION_LOOP_RUN"
    runId = $RunId
    eventKey = $EventKey
    timestamp = $StartedAt
    mode = "CONTROLLED_LOOP"
    domain = "SDU_DOCUMENTLOCATION"
    anchorMode = $AnchorMode
    allowAdxCreate = [bool]$AllowAdxCreate
    runStamp = $RunStamp
    dataverseUrl = $DataverseUrl
    sharepointsiteid = $SharePointSiteId
    relativeurl = $RelativeUrl
    subject = $Subject
    description = $Description
    limits = [ordered]@{
        maxExpedientesCreate = 1
        maxAdxPortalCommentsCreate = if ($AllowAdxCreate) { 1 } else { 0 }
        maxDocumentLocationsCreate = 1
        sharePointFolderCreate = $false
        flowCreateOrRun = $false
        scheduler = $false
        retryAutomatic = $false
        deletePatchPut = $false
        automaticAdxPortalCommentCreate = $false
    }
    state = [ordered]@{
        path = $StatePath
        found = $false
    }
    graph = [ordered]@{}
    anchor = [ordered]@{
        logicalName = $null
        entitySetName = $null
        id = $null
        source = $null
        created = $false
        reused = $false
    }
    expediente = [ordered]@{
        created = $false
        reused = $false
    }
    poc = [ordered]@{
        created = $false
        reused = $false
    }
    documentlocation = [ordered]@{
        created = $false
        reused = $false
    }
    watchdog = [ordered]@{}
    validation = [ordered]@{}
    errors = @()
    outcome = "UNKNOWN"
}

function Save-Evidence {
    if (-not (Test-Path -LiteralPath $EvidenceDir)) {
        New-Item -ItemType Directory -Path $EvidenceDir -Force | Out-Null
    }

    $Result | ConvertTo-Json -Depth 14 | Set-Content -LiteralPath $EvidencePath -Encoding UTF8
}

function Append-Telemetry {
    $telemetryDir = Split-Path -Parent $TelemetryPath
    if (-not (Test-Path -LiteralPath $telemetryDir)) {
        New-Item -ItemType Directory -Path $telemetryDir -Force | Out-Null
    }

    $telemetry = [ordered]@{
        runId = $RunId
        eventKey = $EventKey
        anchorLogicalName = $Result.anchor.logicalName
        anchorId = $Result.anchor.id
        expedienteId = $Result.expediente.expedienteid
        activityId = $Result.poc.activityid
        documentLocationId = $Result.documentlocation.sharepointdocumentlocationid
        created = [bool]($Result.expediente.created -or $Result.poc.created -or $Result.documentlocation.created)
        reused = [bool]($Result.expediente.reused -or $Result.poc.reused -or $Result.documentlocation.reused)
        timestamp = (Get-Date).ToString("o")
        healthSnapshot = $Result.watchdog.health
        locationsReviewed = $Result.watchdog.locationsReviewed
        graphOk = $Result.graph.ok
        outcome = $Result.outcome
        evidence = $EvidencePath
    }

    Add-Content -LiteralPath $TelemetryPath -Value ($telemetry | ConvertTo-Json -Depth 8 -Compress) -Encoding UTF8
}

function Save-LastState {
    $lastDir = Split-Path -Parent $LastStatePath
    if (-not (Test-Path -LiteralPath $lastDir)) {
        New-Item -ItemType Directory -Path $lastDir -Force | Out-Null
    }

    $last = [ordered]@{
        lastRunId = $RunId
        eventKey = $EventKey
        anchorLogicalName = $Result.anchor.logicalName
        anchorId = $Result.anchor.id
        expedienteId = $Result.expediente.expedienteid
        activityId = $Result.poc.activityid
        documentLocationId = $Result.documentlocation.sharepointdocumentlocationid
        health = $Result.watchdog.health
        locationsReviewed = $Result.watchdog.locationsReviewed
        timestamp = (Get-Date).ToString("o")
        outcome = $Result.outcome
        evidence = $EvidencePath
    }

    $last | ConvertTo-Json -Depth 8 | Set-Content -LiteralPath $LastStatePath -Encoding UTF8
}

function Write-ExecutiveOutput {
    if ($JsonOnly) {
        return
    }

    $createdCount = 0
    if ($Result.expediente.created) { $createdCount++ }
    if ($Result.poc.created) { $createdCount++ }
    if ($Result.documentlocation.created) { $createdCount++ }
    $reusedCount = 0
    if ($Result.expediente.reused) { $reusedCount++ }
    if ($Result.poc.reused) { $reusedCount++ }
    if ($Result.documentlocation.reused) { $reusedCount++ }

    $health = [string]$Result.watchdog.health
    $healthColor = "White"
    if ($health -eq "HEALTHY") { $healthColor = "Green" }
    elseif ($health -eq "YELLOW") { $healthColor = "Yellow" }
    elseif ($health -eq "DEGRADED") { $healthColor = "Red" }

    Write-Host ""
    Write-Host "LOOP STATUS"
    Write-Host "- Anchor: $($Result.anchor.logicalName)"
    Write-Host "- Created: $createdCount"
    Write-Host "- Reused: $reusedCount"
    Write-Host "- locationsReviewed: $($Result.watchdog.locationsReviewed)"
    Write-Host "- Health: $health" -ForegroundColor $healthColor
    $graphStatus = if ($Result.graph.ok) { "OK" } else { "FAIL" }
    $graphColor = if ($Result.graph.ok) { "Green" } else { "Red" }
    Write-Host "- Graph: $graphStatus" -ForegroundColor $graphColor
    Write-Host ""
}

function Load-State {
    if (-not (Test-Path -LiteralPath $StatePath)) {
        return [pscustomobject]@{ events = @() }
    }

    try {
        $raw = Get-Content -LiteralPath $StatePath -Raw
        if (-not $raw.Trim()) {
            return [pscustomobject]@{ events = @() }
        }
        return ($raw | ConvertFrom-Json)
    }
    catch {
        throw "State file is not valid JSON: $StatePath"
    }
}

function Save-StateEntry {
    param([object]$State, [object]$Entry)

    $stateDir = Split-Path -Parent $StatePath
    if (-not (Test-Path -LiteralPath $stateDir)) {
        New-Item -ItemType Directory -Path $stateDir -Force | Out-Null
    }

    $events = @()
    if ($State -and $State.events) {
        $events = @($State.events | Where-Object { $_.eventKey -ne $Entry.eventKey })
    }

    $stateOut = [ordered]@{
        updatedAt = (Get-Date).ToString("o")
        events = @($events + [pscustomobject]$Entry)
    }

    $stateOut | ConvertTo-Json -Depth 10 | Set-Content -LiteralPath $StatePath -Encoding UTF8
}

function Get-Token {
    param([string]$Resource)

    $token = (& $AzureCliPath account get-access-token --resource $Resource --query accessToken -o tsv)
    if (-not $token) {
        throw "Azure CLI did not return a token for $Resource"
    }
    return $token
}

function Invoke-DvGet {
    param([string]$Relative)

    Invoke-RestMethod -Method Get -Uri "$DataverseUrl/api/data/v9.2/$Relative" -Headers $script:DvHeaders
}

function Invoke-DvPost {
    param(
        [string]$EntitySet,
        [object]$Body
    )

    $headers = $script:DvHeaders.Clone()
    $headers["Prefer"] = "return=representation"
    $json = $Body | ConvertTo-Json -Depth 10
    Invoke-RestMethod -Method Post -Uri "$DataverseUrl/api/data/v9.2/$EntitySet" -Headers $headers -ContentType "application/json; charset=utf-8" -Body $json
}

function Invoke-GraphGet {
    param([string]$Relative)

    Invoke-RestMethod -Method Get -Uri "$GraphRoot/$Relative" -Headers $script:GraphHeaders
}

function Get-DocumentLocationsForRegardingId {
    param([string]$RegardingId)

    $filter = [uri]::EscapeDataString("_regardingobjectid_value eq $RegardingId")
    $select = [uri]::EscapeDataString("sharepointdocumentlocationid,name,relativeurl,_regardingobjectid_value,_parentsiteorlocation_value")
    $response = Invoke-DvGet "sharepointdocumentlocations?%24select=$select&%24filter=$filter"
    if ($null -eq $response.value) {
        return @()
    }
    return @($response.value)
}

function Get-RegardingNavigationName {
    param([string]$LogicalName)

    $select = [uri]::EscapeDataString("ReferencingAttribute,ReferencedEntity,ReferencingEntityNavigationPropertyName")
    $filter = [uri]::EscapeDataString("ReferencingAttribute eq 'regardingobjectid' and ReferencedEntity eq '$LogicalName'")
    $response = Invoke-DvGet "EntityDefinitions(LogicalName='sharepointdocumentlocation')/ManyToOneRelationships?%24select=$select&%24filter=$filter"
    $relationship = @($response.value | Select-Object -First 1)[0]
    if (-not $relationship -or -not $relationship.ReferencingEntityNavigationPropertyName) {
        throw "Navigation property not found for regardingobjectid target $LogicalName"
    }
    return [string]$relationship.ReferencingEntityNavigationPropertyName
}

function Get-ExpedienteAnchorCapability {
    try {
        $metadata = Invoke-DvGet "EntityDefinitions(LogicalName='cr3c_expediente')?`$select=LogicalName,SchemaName,EntitySetName,PrimaryNameAttribute,PrimaryIdAttribute,IsDocumentManagementEnabled"
        $lookup = Invoke-DvGet "EntityDefinitions(LogicalName='sharepointdocumentlocation')/Attributes(LogicalName='regardingobjectid')/Microsoft.Dynamics.CRM.LookupAttributeMetadata?`$select=LogicalName,Targets"
        $isTarget = (@($lookup.Targets) -contains "cr3c_expediente")
        $isEnabled = ($metadata.IsDocumentManagementEnabled -eq $true)
        return [pscustomobject]@{
            available = [bool]($isEnabled -and $isTarget)
            metadata = $metadata
            isTarget = $isTarget
            isDocumentManagementEnabled = $isEnabled
        }
    }
    catch {
        return [pscustomobject]@{
            available = $false
            metadata = $null
            isTarget = $false
            isDocumentManagementEnabled = $false
            error = $_.Exception.Message
        }
    }
}

function New-SduStateEntry {
    param(
        [string]$AnchorLogicalName,
        [string]$AnchorId,
        [string]$AnchorEntitySetName,
        [string]$SharePointDocumentLocationId,
        [object]$ExistingEvent
    )

    $entry = [ordered]@{
        eventKey = $EventKey
        anchorLogicalName = $AnchorLogicalName
        anchorId = $AnchorId
        anchorEntitySetName = $AnchorEntitySetName
        activityid = $null
        expedienteId = $null
        sharepointdocumentlocationid = $SharePointDocumentLocationId
        firstSeenAt = if ($ExistingEvent -and $ExistingEvent.firstSeenAt) { $ExistingEvent.firstSeenAt } else { (Get-Date).ToString("o") }
        updatedAt = (Get-Date).ToString("o")
    }

    if ($AnchorLogicalName -eq "adx_portalcomment") {
        $entry.activityid = $AnchorId
    }
    elseif ($AnchorLogicalName -eq "cr3c_expediente") {
        $entry.expedienteId = $AnchorId
    }

    return $entry
}

try {
    if (-not (Test-Path -LiteralPath $AzureCliPath)) {
        throw "Azure CLI not found: $AzureCliPath"
    }
    if (-not (Test-Path -LiteralPath $WatchdogPath)) {
        throw "Watchdog not found: $WatchdogPath"
    }

    $azDir = Split-Path -Parent $AzureCliPath
    if ($env:PATH -notlike "*$azDir*") {
        $env:PATH = "$azDir;$env:PATH"
    }

    $state = Load-State
    $existingEvent = $null
    if ($state.events) {
        $existingEvent = @($state.events | Where-Object { $_.eventKey -eq $EventKey } | Select-Object -First 1)[0]
    }
    if ($existingEvent) {
        $Result.state.found = $true
        $Result.state.activityid = $existingEvent.activityid
        $Result.state.sharepointdocumentlocationid = $existingEvent.sharepointdocumentlocationid
    }

    $dvToken = Get-Token -Resource $DataverseUrl
    $graphToken = Get-Token -Resource "https://graph.microsoft.com"
    $script:DvHeaders = @{
        Authorization = "Bearer $dvToken"
        Accept = "application/json"
        "OData-MaxVersion" = "4.0"
        "OData-Version" = "4.0"
    }
    $script:GraphHeaders = @{
        Authorization = "Bearer $graphToken"
        Accept = "application/json"
    }

    $site = Invoke-GraphGet "sites/escribaniabitsch.sharepoint.com:/sites/sistema"
    $drives = Invoke-GraphGet "sites/$($site.id)/drives"
    $drive = @($drives.value | Where-Object { $_.name -eq $RelativeUrl -or $_.webUrl -like "*/$RelativeUrl" } | Select-Object -First 1)[0]
    if (-not $drive) {
        throw "Graph drive not found for $RelativeUrl"
    }
    $driveRoot = Invoke-GraphGet "drives/$($drive.id)/root"
    if (-not $driveRoot.folder) {
        throw "Graph drive root is not a folder for $RelativeUrl"
    }
    $Result.graph = [ordered]@{
        ok = $true
        siteId = $site.id
        siteWebUrl = $site.webUrl
        driveId = $drive.id
        driveName = $drive.name
        driveWebUrl = $drive.webUrl
        folderExists = $true
        folderCreated = $false
    }

    $parent = Invoke-DvGet "sharepointsites($SharePointSiteId)?`$select=sharepointsiteid,name,absoluteurl"
    $Result.parentSharePointSite = [ordered]@{
        ok = $true
        sharepointsiteid = $parent.sharepointsiteid
        name = $parent.name
        absoluteurl = $parent.absoluteurl
    }

    $anchorLogicalName = $null
    $anchorEntitySetName = $null
    $anchorId = $null
    $anchorNavigationName = $null
    $activityId = $null

    $expedienteCapability = $null
    if ($AnchorMode -ne "adx") {
        $expedienteCapability = Get-ExpedienteAnchorCapability
        $Result.anchor.expedienteCapability = [ordered]@{
            available = $expedienteCapability.available
            isTarget = $expedienteCapability.isTarget
            isDocumentManagementEnabled = $expedienteCapability.isDocumentManagementEnabled
            error = $expedienteCapability.error
        }
    }

    if ($existingEvent) {
        if ($existingEvent.anchorLogicalName) {
            $anchorLogicalName = [string]$existingEvent.anchorLogicalName
            $anchorId = [string]$existingEvent.anchorId
            $anchorEntitySetName = [string]$existingEvent.anchorEntitySetName
        }
        elseif ($existingEvent.activityid) {
            $anchorLogicalName = "adx_portalcomment"
            $anchorId = [string]$existingEvent.activityid
            $anchorEntitySetName = "adx_portalcomments"
        }
        elseif ($existingEvent.expedienteId) {
            $anchorLogicalName = "cr3c_expediente"
            $anchorId = [string]$existingEvent.expedienteId
            $anchorEntitySetName = "cr3c_expedientes"
        }
        else {
            throw "Existing state entry has no supported anchor identity for eventKey $EventKey"
        }

        if ($anchorLogicalName -eq "adx_portalcomment") {
            $activityId = $anchorId
            $pocRead = Invoke-DvGet "adx_portalcomments($activityId)?`$select=activityid,subject,description"
            $Result.poc = [ordered]@{
                created = $false
                reused = $true
                activityid = $pocRead.activityid
                subject = $pocRead.subject
                description = $pocRead.description
            }
        }
        elseif ($anchorLogicalName -eq "cr3c_expediente") {
            if (-not $anchorEntitySetName) { $anchorEntitySetName = "cr3c_expedientes" }
            $expRead = Invoke-DvGet "$anchorEntitySetName($anchorId)?`$select=cr3c_expedienteid,cr3c_titulo,cr3c_fechacontrol,cr3c_estadooperativo"
            $Result.expediente = [ordered]@{
                created = $false
                reused = $true
                expedienteid = $expRead.cr3c_expedienteid
                titulo = $expRead.cr3c_titulo
                fechaControl = $expRead.cr3c_fechacontrol
                estadoOperativo = $expRead.cr3c_estadooperativo
            }
        }
        else {
            throw "Unsupported anchor logical name in state: $anchorLogicalName"
        }
    }
    else {
        $useExpediente = $false
        if ($AnchorMode -eq "expediente") {
            if (-not $expedienteCapability.available) {
                throw "AnchorMode expediente requested but cr3c_expediente is not available"
            }
            $useExpediente = $true
        }
        elseif ($AnchorMode -eq "auto" -and $expedienteCapability.available) {
            $useExpediente = $true
        }
        elseif ($AnchorMode -eq "auto") {
            throw "FAIL_CONTROLLED: NO_EXPEDIENTE_AVAILABLE. Automatic adx_portalcomment creation is disabled."
        }

        if ($useExpediente) {
            $metadata = $expedienteCapability.metadata
            $anchorLogicalName = "cr3c_expediente"
            $anchorEntitySetName = $metadata.EntitySetName
            $title = "$Subject $EventKey"
            if ($title.Length -gt 190) { $title = $title.Substring(0, 190) }
            $expPayload = [ordered]@{}
            $expPayload[$metadata.PrimaryNameAttribute] = $title
            $expPayload["cr3c_fechacontrol"] = Get-Date -Format "yyyy-MM-dd"
            $expPayload["cr3c_estadooperativo"] = "AUTO_DOC_LINK"

            $exp = Invoke-DvPost -EntitySet $anchorEntitySetName -Body $expPayload
            $anchorId = $exp.$($metadata.PrimaryIdAttribute)
            if (-not $anchorId) {
                throw "Expediente created but id was not returned"
            }
            $Result.expediente = [ordered]@{
                created = $true
                reused = $false
                expedienteid = $anchorId
                entitySetName = $anchorEntitySetName
                payload = $expPayload
            }
        }
        else {
            if ($AnchorMode -ne "adx") {
                throw "FAIL_CONTROLLED: NO_EXPEDIENTE_AVAILABLE. No supported anchor is available for EventKey $EventKey."
            }
            if (-not $AllowAdxCreate) {
                throw "FAIL_CONTROLLED: ADX_CREATION_DISABLED. AnchorMode adx can reuse historical state, but new adx_portalcomment creation requires -AllowAdxCreate."
            }
            $anchorLogicalName = "adx_portalcomment"
            $anchorEntitySetName = "adx_portalcomments"
            $pocPayload = [ordered]@{
                subject = $Subject
                description = $Description
            }
            $poc = Invoke-DvPost -EntitySet "adx_portalcomments" -Body $pocPayload
            $activityId = $poc.activityid
            $anchorId = $activityId
            if (-not $activityId) {
                throw "POC created but activityid was not returned"
            }
            $Result.poc = [ordered]@{
                created = $true
                reused = $false
                activityid = $activityId
                payload = $pocPayload
            }
        }

        Save-StateEntry -State $state -Entry (New-SduStateEntry -AnchorLogicalName $anchorLogicalName -AnchorId $anchorId -AnchorEntitySetName $anchorEntitySetName -SharePointDocumentLocationId $null -ExistingEvent $existingEvent)
        $state = Load-State
    }

    $anchorNavigationName = Get-RegardingNavigationName -LogicalName $anchorLogicalName
    $Result.anchor = [ordered]@{
        logicalName = $anchorLogicalName
        entitySetName = $anchorEntitySetName
        id = $anchorId
        navigationName = $anchorNavigationName
        mode = $AnchorMode
        expedienteAvailable = if ($expedienteCapability) { [bool]$expedienteCapability.available } else { $null }
        adxCreationAllowed = [bool]$AllowAdxCreate
        source = if ($existingEvent) { "state" } elseif ($anchorLogicalName -eq "cr3c_expediente") { "domain_primary" } else { "adx_explicit_create" }
        created = [bool]($Result.expediente.created -or $Result.poc.created)
        reused = [bool]($Result.expediente.reused -or $Result.poc.reused)
    }

    $stateDocLocationId = $null
    $stateDocLocation = $null
    if ($existingEvent -and $existingEvent.sharepointdocumentlocationid) {
        $stateDocLocationId = [string]$existingEvent.sharepointdocumentlocationid
        $stateDocLocation = Invoke-DvGet "sharepointdocumentlocations($stateDocLocationId)?`$select=sharepointdocumentlocationid,name,relativeurl,_regardingobjectid_value,_parentsiteorlocation_value"
        if ($stateDocLocation._regardingobjectid_value -ne $anchorId) {
            throw "State DocumentLocation does not point to anchor $anchorLogicalName/$anchorId"
        }
    }

    $existingLocations = @(Get-DocumentLocationsForRegardingId -RegardingId $anchorId)
    $Result.documentlocation.getBeforePost = [ordered]@{
        filter = "_regardingobjectid_value eq $anchorId"
        anchorLogicalName = $anchorLogicalName
        count = $existingLocations.Count
    }

    if ($existingLocations.Count -gt 1) {
        throw "Duplicate DocumentLocations for anchor $anchorLogicalName/$anchorId"
    }

    if ($stateDocLocation) {
        $docLocationId = $stateDocLocation.sharepointdocumentlocationid
        $Result.documentlocation.created = $false
        $Result.documentlocation.reused = $true
        $Result.documentlocation.reusedFromState = $true
        $Result.documentlocation.sharepointdocumentlocationid = $docLocationId
    }
    elseif ($existingLocations.Count -eq 1) {
        $docLocationId = $existingLocations[0].sharepointdocumentlocationid
        $Result.documentlocation.created = $false
        $Result.documentlocation.reused = $true
        $Result.documentlocation.sharepointdocumentlocationid = $docLocationId
    }
    else {
        $docLocationId = [guid]::NewGuid().ToString()
        $docPayload = [ordered]@{
            sharepointdocumentlocationid = $docLocationId
            name = "AUTO_DOC_LINK_LOCATION"
            servicetype = 0
            locationtype = 0
            relativeurl = $RelativeUrl
            description = $Description
            "parentsiteorlocation_sharepointsite@odata.bind" = "/sharepointsites($SharePointSiteId)"
        }
        $docPayload["$anchorNavigationName@odata.bind"] = "/$anchorEntitySetName($anchorId)"

        $created = Invoke-DvPost -EntitySet "sharepointdocumentlocations" -Body $docPayload
        $Result.documentlocation.created = $true
        $Result.documentlocation.reused = $false
        $Result.documentlocation.sharepointdocumentlocationid = $docLocationId
        $Result.documentlocation.responseId = $created.sharepointdocumentlocationid
        $Result.documentlocation.payload = $docPayload

        Save-StateEntry -State $state -Entry (New-SduStateEntry -AnchorLogicalName $anchorLogicalName -AnchorId $anchorId -AnchorEntitySetName $anchorEntitySetName -SharePointDocumentLocationId $docLocationId -ExistingEvent $existingEvent)
        $state = Load-State
        Start-Sleep -Seconds 2
    }

    $postLocations = @(Get-DocumentLocationsForRegardingId -RegardingId $anchorId)
    $lookupDelayed = $false
    if ($postLocations.Count -eq 0 -and $docLocationId) {
        $directPostcheck = Invoke-DvGet "sharepointdocumentlocations($docLocationId)?`$select=sharepointdocumentlocationid,_regardingobjectid_value"
        if ($directPostcheck._regardingobjectid_value -eq $anchorId) {
            $lookupDelayed = $true
        }
    }
    elseif ($postLocations.Count -gt 1) {
        throw "Postcheck duplicate count for anchor $anchorLogicalName/$anchorId is $($postLocations.Count)"
    }

    $readback = Invoke-DvGet "sharepointdocumentlocations($docLocationId)?`$select=sharepointdocumentlocationid,name,relativeurl,_regardingobjectid_value,_parentsiteorlocation_value,statecode,statuscode"
    $retrieve = Invoke-DvGet "sharepointdocumentlocations($docLocationId)/Microsoft.Dynamics.CRM.RetrieveAbsoluteAndSiteCollectionUrl()"
    $Result.documentlocation.readback = [ordered]@{
        sharepointdocumentlocationid = $readback.sharepointdocumentlocationid
        name = $readback.name
        relativeurl = $readback.relativeurl
        regardingobjectid = $readback._regardingobjectid_value
        parentsiteorlocation = $readback._parentsiteorlocation_value
        statecode = $readback.statecode
        statuscode = $readback.statuscode
        retrieveAbsolute = [ordered]@{
            AbsoluteUrl = $retrieve.AbsoluteUrl
            SiteCollectionUrl = $retrieve.SiteCollectionUrl
        }
    }

    Save-StateEntry -State $state -Entry (New-SduStateEntry -AnchorLogicalName $anchorLogicalName -AnchorId $anchorId -AnchorEntitySetName $anchorEntitySetName -SharePointDocumentLocationId $docLocationId -ExistingEvent $existingEvent)

    if (-not $SkipWatchdog) {
        & powershell.exe -NoProfile -ExecutionPolicy Bypass -File $WatchdogPath -DataverseUrl $DataverseUrl -UseAzureCliToken | Out-Null
        $exitCode = $LASTEXITCODE
        $healthPath = Join-Path (Split-Path -Parent $WatchdogPath) "logs\sharepoint_link_health.json"
        $health = if (Test-Path -LiteralPath $healthPath) { Get-Content -LiteralPath $healthPath -Raw | ConvertFrom-Json } else { $null }
        $latestEvidence = Get-ChildItem -LiteralPath $EvidenceDir -Filter "sharepoint_link_watchdog_*.json" -ErrorAction SilentlyContinue |
            Sort-Object LastWriteTime -Descending |
            Select-Object -First 1

        $Result.watchdog = [ordered]@{
            exitCode = $exitCode
            health = $health.health
            locationsReviewed = $health.locationsReviewed
            evidence = $latestEvidence.FullName
        }
    }

    $Result.validation = [ordered]@{
        anchorLogicalName = $anchorLogicalName
        anchorId = $anchorId
        duplicateDocumentLocationsForRegarding = ($postLocations.Count -gt 1)
        documentLocationCountForRegarding = if ($lookupDelayed) { 1 } else { $postLocations.Count }
        lookupDelayedButDirectReadbackOk = $lookupDelayed
        graphOk = [bool]$Result.graph.ok
        folderCreated = $false
        documentLocationCreated = [bool]$Result.documentlocation.created
        documentLocationReused = [bool]$Result.documentlocation.reused
    }

    if ($Result.validation.duplicateDocumentLocationsForRegarding) {
        $Result.outcome = "FAIL_DUPLICATE"
    }
    elseif (-not $Result.graph.ok) {
        $Result.outcome = "FAIL_GRAPH"
    }
    else {
        $Result.outcome = "PASS"
    }

    Append-Telemetry
    Save-LastState
    Save-Evidence
    Write-ExecutiveOutput
    [pscustomobject]@{
        runId = $RunId
        outcome = $Result.outcome
        eventKey = $EventKey
        anchorLogicalName = $anchorLogicalName
        anchorId = $anchorId
        evidence = $EvidencePath
        activityid = $activityId
        expedienteid = $Result.expediente.expedienteid
        sharepointdocumentlocationid = $docLocationId
        anchorCreated = $Result.anchor.created
        anchorReused = $Result.anchor.reused
        pocCreated = $Result.poc.created
        pocReused = $Result.poc.reused
        expedienteCreated = $Result.expediente.created
        expedienteReused = $Result.expediente.reused
        documentLocationCreated = $Result.documentlocation.created
        documentLocationReused = $Result.documentlocation.reused
        duplicateDocumentLocationsForRegarding = $Result.validation.duplicateDocumentLocationsForRegarding
        health = $Result.watchdog.health
        locationsReviewed = $Result.watchdog.locationsReviewed
        watchdogEvidence = $Result.watchdog.evidence
        telemetryPath = $TelemetryPath
        lastStatePath = $LastStatePath
    } | ConvertTo-Json -Depth 6
}
catch {
    $Result.outcome = "FAIL"
    $Result.errors += [ordered]@{
        message = $_.Exception.Message
        at = (Get-Date).ToString("o")
        }
    Save-Evidence
    try {
        Append-Telemetry
        Save-LastState
    }
    catch {
        # Do not hide the original failure if secondary logging fails.
    }
    Write-ExecutiveOutput
    [pscustomobject]@{
        runId = $RunId
        outcome = "FAIL"
        eventKey = $EventKey
        anchorLogicalName = $Result.anchor.logicalName
        anchorId = $Result.anchor.id
        evidence = $EvidencePath
        error = $_.Exception.Message
        activityid = $Result.poc.activityid
        expedienteid = $Result.expediente.expedienteid
        sharepointdocumentlocationid = $Result.documentlocation.sharepointdocumentlocationid
    } | ConvertTo-Json -Depth 6
    exit 1
}
